# Generated by Django 5.1.5 on 2025-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(default='./static/image/defaultavatar.png'),
        ),
    ]
