version: '3.8'

services:
  db:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: ft_transcendence
      POSTGRES_PASSWORD: ft_transcendence
      POSTGRES_DB: backend_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ft_transcendence -d backend_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app-network

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    ports:
      - "8082:8080"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP Server
      - "8025:8025"  # Interface Web
    networks:
      - app-network
    restart: always

  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/app/swagger.json
    volumes:
      - ./Backend/swagger.json:/app/swagger.json
    networks:
      - app-network
    restart: always

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DATABASE_URL=postgres://ft_transcendence:yourpassword@db:5432/backend_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./Backend/backend:/app/backend
      - static_volume:/app/backend/static
      - media_volume:/app/backend/media
    command: >
      sh -c "
        mkdir -p /app/backend/static &&
        mkdir -p /app/backend/media &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      mailhog:
        condition: service_started
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports: 
      - "5173:5173"
    networks:
      - app-network
    volumes: 
      - ./Frontend:/app
      - frontend_modules:/app/node_modules
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data:
  frontend_modules:
  static_volume:
  media_volume:
  redis_data:

networks:
  app-network:
    driver: bridge