from django.urls import path
from .views import (
    FortyTwoLoginView, 
    FortyTwoCallbackView, 
    LoginView, 
    UserProfileView, 
    LogoutView,
    UpdateAvatarView,
    SignUpView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    RequestProfileChangeView,
    ConfirmProfileChangeView,
    RequestPasswordChangeView,
    ConfirmPasswordChangeView,
    DeleteAccountConfirmView,
    VerifyTwoFactorView,
    SearchUsersView,
    UserProfileDetailView,
    UserProfileByIntraIdView,
    UserStatusView,
    NotificationViewSet,
    FriendshipView,
    FriendRequestView,
    PendingFriendRequestsView,
    SentFriendRequestsView,
    FriendRequestActionView,
    MarkNotificationAsReadView,
    RemoveFriendView,
    UserIPView
)

urlpatterns = [
    path('users/signup/', SignUpView.as_view(), name='signup'),
    path('auth/42/login/', FortyTwoLoginView.as_view(), name='ft_login'),
    path('auth/42/callback/', FortyTwoCallbackView.as_view(), name='ft_callback'),
    path('users/login/', LoginView.as_view(), name='login'),
    path('users/profile/', UserProfileView.as_view(), name='user-profile'),
    path('users/logout/', LogoutView.as_view(), name='logout'),
    path('users/avatar/', UpdateAvatarView.as_view(), name='update-avatar'),
    path('users/password-reset/', PasswordResetRequestView.as_view(), name='password-reset-request'),
	path('users/password-reset-confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
	path('users/request-change/', RequestProfileChangeView.as_view(), name='request-profile-change'),
	path('users/confirm-profile-change/', ConfirmProfileChangeView.as_view()),
	path('users/request-password-change/', RequestPasswordChangeView.as_view(), name='request-password-change'),
	path('users/confirm-password-change/', ConfirmPasswordChangeView.as_view(), name='confirm-password-change'),
	path('users/confirm-delete/', DeleteAccountConfirmView.as_view(), name='confirm-delete'),
	path('users/verify-2fa/', VerifyTwoFactorView.as_view(), name='verify-2fa'),
	path('users/search/', SearchUsersView.as_view(), name='search-users'),
	path('users/status/', UserStatusView.as_view(), name='user-status'),
	path('notifications/', NotificationViewSet.as_view({'get': 'list'}), name='notifications'),
	path('users/friends/', FriendshipView.as_view(), name='friends-list'),
    path('users/friends/requests/', FriendRequestView.as_view(), name='friend-request'),
    path('users/friends/requests/pending/', PendingFriendRequestsView.as_view(), name='pending-friend-requests'),
    path('users/friends/requests/sent/', SentFriendRequestsView.as_view(), name='sent-friend-requests'),
    path('users/friends/requests/<int:friendship_id>/', FriendRequestActionView.as_view(), name='friend-request-action'),
	path('users/<str:intra_id>/', UserProfileByIntraIdView.as_view(), name='user-profile-by-intra'),
	path('notifications/read/', MarkNotificationAsReadView.as_view(), name='mark-notifications-read'),
    path('notifications/<int:notification_id>/read/', MarkNotificationAsReadView.as_view(), name='mark-single-notification-read'),
	path('users/friends/remove/<int:friendship_id>/', RemoveFriendView.as_view(), name='remove-friend-by-friendship'),
	path('users/friends/remove/user/<int:user_id>/', RemoveFriendView.as_view(), name='remove-friend-by-user'),
	path('users/ip/', UserIPView.as_view(), name='user-ip'),
]