from django.urls import path
from .views import (
    FortyTwoLoginView, 
    FortyTwoCallbackView, 
    LoginView, 
    UserProfileView, 
    LogoutView,
    UpdateAvatarView,
    SignUpView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    RequestProfileChangeView,
    ConfirmProfileChangeView,
    RequestPasswordChangeView,
    ConfirmPasswordChangeView,
    DeleteAccountConfirmView,
    VerifyTwoFactorView,
    SearchUsersView,
    UserProfileDetailView,
    UserProfileByIntraIdView,
    UserStatusView,
    NotificationViewSet
)

urlpatterns = [
    path('users/signup/', SignUpView.as_view(), name='signup'),
    path('auth/42/login/', FortyTwoLoginView.as_view(), name='ft_login'),
    path('auth/42/callback/', FortyTwoCallbackView.as_view(), name='ft_callback'),
    path('users/login/', LoginView.as_view(), name='login'),
    path('users/profile/', UserProfileView.as_view(), name='user-profile'),
    path('users/logout/', LogoutView.as_view(), name='logout'),
    path('users/avatar/', UpdateAvatarView.as_view(), name='update-avatar'),
    path('users/password-reset/', PasswordResetRequestView.as_view(), name='password-reset-request'),
	path('users/password-reset-confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
	path('users/request-change/', RequestProfileChangeView.as_view(), name='request-profile-change'),
	path('users/confirm-profile-change/', ConfirmProfileChangeView.as_view()),
	path('users/request-password-change/', RequestPasswordChangeView.as_view(), name='request-password-change'),
	path('users/confirm-password-change/', ConfirmPasswordChangeView.as_view(), name='confirm-password-change'),
	path('users/confirm-delete/', DeleteAccountConfirmView.as_view(), name='confirm-delete'),
	path('users/verify-2fa/', VerifyTwoFactorView.as_view(), name='verify-2fa'),
	path('users/search/', SearchUsersView.as_view(), name='search-users'),
	path('users/<str:intra_id>/', UserProfileByIntraIdView.as_view(), name='user-profile-by-intra'),
	path('users/status/', UserStatusView.as_view(), name='user-status'),
	path('notifications/', NotificationViewSet.as_view({'get': 'list'}), name='notifications'),
]